#!/bin/bash
sudo mv /home/sis/samba/hostname /etc/hostname
sudo mv /home/sis/samba/hosts /etc/hosts
sudo apt-get update
sudo apt-get install samba -y
sudo mkdir /srv/kozos
sudo chmod 777 /srv/kozos
sudo mkdir /srv/readonly
sudo chmod 755 /srv/readonly
mv /home/sis/samba/smb.conf /etc/samba/smb.conf
sudo service smbd restart
sudo adduser user2 --gecos "" --disabled-password
echo "user2:123" | sudo chpasswd
sudo mkdir /srv/user2
sudo chown user2 /srv/user2
sudo chmod 700 /srv/user2
echo -e "123\n123" | smbpasswd -s -a user2
sudo service smbd restart
